version: '2'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            db:
                condition: service_healthy
        command: sh -c 'python ./app.py'
    db:
        image: mysql:8.0.23
        environment:
            MYSQL_DATABASE: user_login
            MYSQL_USER: venugopal
            MYSQL_PASSWORD: Gopalvenu@113
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_USER: root
        command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci', '--default-authentication-plugin=mysql_native_password']
        healthcheck:
            test: "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 10s
            retries: 100
